/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ControleEstoque.visao;

import br.com.ControleEstoque.controle.ControleFornecedores;
import br.com.ControleEstoque.modelo.ModeloFornecedores;
import br.com.ControleEstoque.dal.ConexaoBD;
import br.com.ControleEstoque.modelo.ModeloTabela;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Cleiton
 */
public class FrmFornecedores extends javax.swing.JFrame {

    ConexaoBD conex = new ConexaoBD();
    ModeloFornecedores mod = new ModeloFornecedores();
    ControleFornecedores control = new ControleFornecedores();

    /**
     * Creates new form FrmFornecedores
     */
    public FrmFornecedores() {
	initComponents();
	preencherBairros();
	preencherTabela("select * from tbfornecedores inner join bairro on id_bairrof = id_bairro");
    }//FIM DA INICIALIZACAO

    public void preencherBairros() {
	conex.Conexao();

	try {
	    conex.executaSql("select * from bairro order by nome_bairro");
	    conex.rs.first();
	    cb_bairroFornecedor.removeAllItems();
	    do {
		cb_bairroFornecedor.addItem(conex.rs.getString("nome_bairro"));
	    } while (conex.rs.next());
	} catch (SQLException ex) {
	    JOptionPane.showMessageDialog(null, "Erro ao preencher a combobox bairro" + ex);
	}
	conex.desconecta();
    }// FIM DO METODO

    public void preencherTabela(String sql) {
	ArrayList dados = new ArrayList();
	String[] colunas = new String[]{"Id", "Fornecedor", "Endereço","Nº", "CNPJ", "Celular","Telefone"};
	conex.Conexao();
	conex.executaSql(sql);
	try {
	    conex.rs.first();
	    do {
		dados.add(new Object[]{conex.rs.getInt("id_fornecedor"), conex.rs.getString("nome_fornecedor"), conex.rs.getString("endereco_fornecedor"), conex.rs.getString("numero_fornecedor"), conex.rs.getString("cnpj_fornecedor"), conex.rs.getString("telefone1_fornecedor"), conex.rs.getString("telefone2_fornecedor")});
	    } while (conex.rs.next());

	} catch (Exception ex) {
	    //JOptionPane.showMessageDialog(null, "Não ha nenhum fornecedor cadastrado");
	}
	ModeloTabela modelo = new ModeloTabela(dados, colunas);
	tbl_fornecedores.setModel(modelo);
	tbl_fornecedores.getColumnModel().getColumn(0).setPreferredWidth(65);
	tbl_fornecedores.getColumnModel().getColumn(0).setResizable(false);

	tbl_fornecedores.getColumnModel().getColumn(1).setPreferredWidth(210);
	tbl_fornecedores.getColumnModel().getColumn(1).setResizable(false);

	tbl_fornecedores.getColumnModel().getColumn(2).setPreferredWidth(210);
	tbl_fornecedores.getColumnModel().getColumn(2).setResizable(false);

	tbl_fornecedores.getColumnModel().getColumn(3).setPreferredWidth(70);
	tbl_fornecedores.getColumnModel().getColumn(3).setResizable(false);

	tbl_fornecedores.getColumnModel().getColumn(4).setPreferredWidth(200);
	tbl_fornecedores.getColumnModel().getColumn(4).setResizable(false);
	
	tbl_fornecedores.getColumnModel().getColumn(5).setPreferredWidth(150);
	tbl_fornecedores.getColumnModel().getColumn(5).setResizable(false);
	
	tbl_fornecedores.getColumnModel().getColumn(6).setPreferredWidth(150);
	tbl_fornecedores.getColumnModel().getColumn(6).setResizable(false);

	tbl_fornecedores.getTableHeader().setReorderingAllowed(false);
	tbl_fornecedores.setAutoResizeMode(tbl_fornecedores.AUTO_RESIZE_OFF);
	tbl_fornecedores.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
	conex.desconecta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_horario = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lbl_data = new javax.swing.JLabel();
        lbl_idFornecedor = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_nomeFornecedor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cb_bairroFornecedor = new javax.swing.JComboBox<>();
        txt_pesquisar = new javax.swing.JTextField();
        bt_pesquisar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_enderecoFornecedor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_numeroFornecedor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_cidade = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_estado = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_celular = new javax.swing.JFormattedTextField();
        txt_telefoneFornecedor = new javax.swing.JFormattedTextField();
        txt_cnpjFornecedor = new javax.swing.JFormattedTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        bt_novo = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        bt_salvar = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        bt_cancelar = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        bt_editar = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        bt_excluir = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbl_fornecedores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setPreferredSize(new java.awt.Dimension(1340, 110));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Formulário Cadastro de Fornecedores");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lbl_horario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_horario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_horario.setText("Data");
        lbl_horario.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_horario, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_horario, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lbl_data.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_data.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_data.setText("Data");
        lbl_data.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_data, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        lbl_idFornecedor.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_idFornecedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_idFornecedor.setText("01");
        lbl_idFornecedor.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Cod :");
        jLabel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_idFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(207, 207, 207)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_idFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(19, 19, 19))))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Digite um Fornecedor :");
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txt_nomeFornecedor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_nomeFornecedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nomeFornecedor.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Selecione um Bairro :");
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        cb_bairroFornecedor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cb_bairroFornecedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_bairroFornecedor.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        cb_bairroFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cb_bairroFornecedorMouseEntered(evt);
            }
        });

        txt_pesquisar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_pesquisar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_pesquisar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        bt_pesquisar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bt_pesquisar.setText("Pesquisar");
        bt_pesquisar.setToolTipText("Pesquise por um Cliente");
        bt_pesquisar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        bt_pesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pesquisarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Digite um Endereço :");
        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txt_enderecoFornecedor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_enderecoFornecedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_enderecoFornecedor.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Nº :");
        jLabel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txt_numeroFornecedor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_numeroFornecedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_numeroFornecedor.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Cidade :");
        jLabel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txt_cidade.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_cidade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_cidade.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txt_cidade.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Estado :");
        jLabel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txt_estado.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_estado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_estado.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txt_estado.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Pesquise um Fornecedor :");
        jLabel10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Celular :");
        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Telefone Fixo :");
        jLabel11.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("CNPJ :");
        jLabel12.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txt_celular.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        try {
            txt_celular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_celular.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_celular.setToolTipText("");
        txt_celular.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_celular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_celularActionPerformed(evt);
            }
        });

        txt_telefoneFornecedor.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        try {
            txt_telefoneFornecedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_telefoneFornecedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_telefoneFornecedor.setToolTipText("");
        txt_telefoneFornecedor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_telefoneFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefoneFornecedorActionPerformed(evt);
            }
        });

        txt_cnpjFornecedor.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        try {
            txt_cnpjFornecedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_cnpjFornecedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_cnpjFornecedor.setToolTipText("");
        txt_cnpjFornecedor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_cnpjFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cnpjFornecedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(txt_nomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(txt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(cb_bairroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(txt_enderecoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(txt_numeroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(73, 73, 73)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_celular)
                            .addComponent(txt_telefoneFornecedor)
                            .addComponent(txt_cnpjFornecedor)
                            .addComponent(txt_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(bt_pesquisar)
                        .addGap(324, 324, 324))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_celular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txt_nomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_enderecoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txt_telefoneFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_numeroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txt_cnpjFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cb_bairroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txt_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(bt_pesquisar)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txt_celular, txt_cidade, txt_cnpjFornecedor, txt_enderecoFornecedor, txt_estado, txt_nomeFornecedor, txt_numeroFornecedor, txt_pesquisar, txt_telefoneFornecedor});

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        bt_novo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bt_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ControleEstoque/icones/add.png"))); // NOI18N
        bt_novo.setText("Novo");
        bt_novo.setToolTipText("Faça um novo Registro");
        bt_novo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        bt_novo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_novoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_novo, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_novo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        bt_salvar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bt_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ControleEstoque/icones/save-icon.png"))); // NOI18N
        bt_salvar.setText("Salvar");
        bt_salvar.setToolTipText("Salve um novo registro");
        bt_salvar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        bt_salvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_salvar, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_salvar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        bt_cancelar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bt_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ControleEstoque/icones/cancel-icon.png"))); // NOI18N
        bt_cancelar.setText("Cancelar");
        bt_cancelar.setToolTipText("Limpar os Campos");
        bt_cancelar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        bt_cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_cancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        bt_editar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bt_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ControleEstoque/icones/File-edit-icon.png"))); // NOI18N
        bt_editar.setText("Editar");
        bt_editar.setToolTipText("Atualizar um registro");
        bt_editar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        bt_editar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_editar, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_editar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        bt_excluir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bt_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ControleEstoque/icones/delete.png"))); // NOI18N
        bt_excluir.setText("Excluir");
        bt_excluir.setToolTipText("Ecluir permanentemente um registro");
        bt_excluir.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        bt_excluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_excluir, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_excluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fornecedores  Cadastrados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        tbl_fornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_fornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_fornecedoresMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tbl_fornecedores);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 1058, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1330, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1366, 799));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cb_bairroFornecedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_bairroFornecedorMouseEntered
	try {
	    conex.Conexao();
	    conex.executaSql("select * from bairro inner join cidade on id_cidade = id_cidadef inner join estado on id_estadof=id_estado where nome_bairro = '" + cb_bairroFornecedor.getSelectedItem() + "'");
	    conex.rs.first();
	    txt_cidade.setText(conex.rs.getString("nome_cidade"));
	    txt_estado.setText(conex.rs.getString("nome_estado"));
	} catch (SQLException ex) {
	    JOptionPane.showMessageDialog(null, "Erro ao selecionar a combobox bairro" + ex);
	}
    }//GEN-LAST:event_cb_bairroFornecedorMouseEntered

    private void bt_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pesquisarActionPerformed
	String pesquisa = txt_pesquisar.getText();
	if (pesquisa.equals("")) {
	    JOptionPane.showMessageDialog(null, "Digite um Cliente a ser pesquisado");
	} else {
	    mod.setPesquisa(txt_pesquisar.getText());
	    ModeloFornecedores model = control.pesquisarFornecedores(mod);
	    lbl_idFornecedor.setText(String.valueOf(model.getId_fornecedor()));
	    txt_nomeFornecedor.setText(model.getNome_fornecedor());
	    txt_enderecoFornecedor.setText(model.getEndereco_fornecedor());
	    txt_numeroFornecedor.setText(model.getEndereco_fornecedor());
	    txt_cnpjFornecedor.setText(model.getCnpj_fornecedor());
	    txt_celular.setText(model.getTelefone1_fornecedor());
	    txt_telefoneFornecedor.setText(model.getTelefone2_fornecedor());
	    cb_bairroFornecedor.setSelectedItem(model.getNome_bairro());
	    txt_cidade.setText(model.getNome_cidade());
	    txt_estado.setText(model.getNome_estado());
	    bt_editar.setEnabled(true);
	    bt_excluir.setEnabled(true);
	}
    }//GEN-LAST:event_bt_pesquisarActionPerformed

    private void txt_celularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_celularActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_txt_celularActionPerformed

    private void txt_telefoneFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefoneFornecedorActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_txt_telefoneFornecedorActionPerformed

    private void txt_cnpjFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cnpjFornecedorActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_txt_cnpjFornecedorActionPerformed

    private void bt_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_novoActionPerformed
	lbl_idFornecedor.setText("");
	txt_nomeFornecedor.setText("");
	txt_enderecoFornecedor.setText("");
	txt_numeroFornecedor.setText("");
	txt_cnpjFornecedor.setText("");
	txt_celular.setText("");
	txt_telefoneFornecedor.setText("");
	txt_pesquisar.setText("");
	txt_pesquisar.setEnabled(false);
	txt_nomeFornecedor.setEnabled(true);
	txt_enderecoFornecedor.setEnabled(true);
	txt_numeroFornecedor.setEnabled(true);
	txt_cnpjFornecedor.setEnabled(true);
	txt_celular.setEnabled(true);
	txt_telefoneFornecedor.setEnabled(true);
	cb_bairroFornecedor.setEnabled(true);
	bt_salvar.setEnabled(true);
	bt_cancelar.setEnabled(true);
	bt_editar.setEnabled(false);
	bt_excluir.setEnabled(false);
	bt_pesquisar.setEnabled(false);
    }//GEN-LAST:event_bt_novoActionPerformed

    private void bt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salvarActionPerformed
	if (txt_nomeFornecedor.getText().isEmpty() || txt_enderecoFornecedor.getText().isEmpty()) {
	    JOptionPane.showMessageDialog(null, "há campos a serem preenchidos");
	} else {
	    mod.setNome_fornecedor(txt_nomeFornecedor.getText());
	    mod.setEndereco_fornecedor(txt_enderecoFornecedor.getText());
	    mod.setNumero_fornecedor(txt_numeroFornecedor.getText());
	    mod.setCnpj_fornecedor(txt_cnpjFornecedor.getText());
	    mod.setTelefone1_fornecedor(txt_celular.getText());
	    mod.setTelefone2_fornecedor(txt_telefoneFornecedor.getText());
	    mod.setNome_bairro(cb_bairroFornecedor.getSelectedItem().toString());
	    control.AdicionarFornecedores(mod);
	    preencherTabela("select * from tbfornecedores inner join bairro on id_bairrof = id_bairro");
	}
	lbl_idFornecedor.setText("");
	txt_nomeFornecedor.setText("");
	txt_enderecoFornecedor.setText("");
	txt_numeroFornecedor.setText("");
	txt_cnpjFornecedor.setText("");
	txt_celular.setText("");
	txt_telefoneFornecedor.setText("");
    }//GEN-LAST:event_bt_salvarActionPerformed

    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
	lbl_idFornecedor.setText("");
	txt_nomeFornecedor.setText("");
	txt_enderecoFornecedor.setText("");
	txt_numeroFornecedor.setText("");
	txt_cnpjFornecedor.setText("");
	txt_celular.setText("");
	txt_telefoneFornecedor.setText("");
	txt_pesquisar.setText("");
	txt_pesquisar.setEnabled(true);
	txt_nomeFornecedor.setEnabled(false);
	txt_enderecoFornecedor.setEnabled(false);
	txt_numeroFornecedor.setEnabled(false);
	txt_cnpjFornecedor.setEnabled(false);
	txt_celular.setEnabled(false);
	txt_telefoneFornecedor.setEnabled(false);
	cb_bairroFornecedor.setEnabled(false);
	txt_cidade.setEnabled(false);
	txt_estado.setEnabled(true);
	bt_salvar.setEnabled(false);
	bt_cancelar.setEnabled(true);
	bt_editar.setEnabled(false);
	bt_excluir.setEnabled(false);
	bt_pesquisar.setEnabled(true);
    }//GEN-LAST:event_bt_cancelarActionPerformed

    private void bt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editarActionPerformed
	mod.setId_fornecedor(Integer.parseInt(lbl_idFornecedor.getText()));
	mod.setNome_fornecedor(txt_nomeFornecedor.getText());
	mod.setEndereco_fornecedor(txt_enderecoFornecedor.getText());
	mod.setNumero_fornecedor(txt_numeroFornecedor.getText());
	mod.setCnpj_fornecedor(txt_cnpjFornecedor.getText());
	mod.setTelefone1_fornecedor(txt_celular.getText());
	mod.setTelefone2_fornecedor(txt_telefoneFornecedor.getText());
	mod.setNome_bairro(cb_bairroFornecedor.getSelectedItem().toString());
	control.EditarFornecedor(mod);
	preencherTabela("select * from tbfornecedores inner join bairro on id_bairrof = id_bairro");
    }//GEN-LAST:event_bt_editarActionPerformed

    private void bt_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluirActionPerformed
	mod.setId_fornecedor(Integer.parseInt(lbl_idFornecedor.getText()));
	mod.setNome_fornecedor(txt_nomeFornecedor.getText());
	mod.setEndereco_fornecedor(txt_enderecoFornecedor.getText());
	mod.setNumero_fornecedor(txt_numeroFornecedor.getText());
	mod.setCnpj_fornecedor(txt_cnpjFornecedor.getText());
	mod.setTelefone1_fornecedor(txt_celular.getText());
	mod.setTelefone2_fornecedor(txt_telefoneFornecedor.getText());
	mod.setNome_bairro(cb_bairroFornecedor.getSelectedItem().toString());
	control.ExcluirFornecedores(mod);
	lbl_idFornecedor.setText("");
	txt_nomeFornecedor.setText("");
	txt_enderecoFornecedor.setText("");
	txt_numeroFornecedor.setText("");
	txt_cnpjFornecedor.setText("");
	txt_celular.setText("");
	txt_telefoneFornecedor.setText("");
	txt_pesquisar.setText("");
	preencherTabela("select * from tbfornecedores inner join bairro on id_bairrof = id_bairro");
    }//GEN-LAST:event_bt_excluirActionPerformed

    private void tbl_fornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_fornecedoresMouseClicked
	String nome_fornecedor = "" + tbl_fornecedores.getValueAt(tbl_fornecedores.getSelectedRow(), 1);
	conex.Conexao();
	conex.executaSql("select * from tbfornecedores inner join bairro on id_bairrof = id_bairro inner join cidade on id_cidadef = id_cidade inner join estado on id_estadof = id_estado  where nome_fornecedor='" + nome_fornecedor + "'");
	try {
	    conex.rs.first();
	    lbl_idFornecedor.setText(Integer.toString(conex.rs.getInt("id_fornecedor")));
	    txt_nomeFornecedor.setText(conex.rs.getString("nome_fornecedor"));
	    txt_enderecoFornecedor.setText(conex.rs.getString("endereco_fornecedor"));
	    txt_numeroFornecedor.setText(conex.rs.getString("numero_fornecedor"));
	    txt_cnpjFornecedor.setText(conex.rs.getString("cnpj_fornecedor"));
	    txt_celular.setText(conex.rs.getString("telefone1_fornecedor"));
	    txt_telefoneFornecedor.setText(conex.rs.getString("telefone2_fornecedor"));
	    cb_bairroFornecedor.setSelectedItem(conex.rs.getString("nome_bairro"));
	    txt_cidade.setText(conex.rs.getString("nome_cidade"));
	    txt_estado.setText(conex.rs.getString("nome_estado"));
	} catch (Exception ex) {
	    JOptionPane.showMessageDialog(null, "Erro ao setar campos " + ex);
	}
	conex.desconecta();
	bt_editar.setEnabled(true);
	bt_excluir.setEnabled(true);
	bt_salvar.setEnabled(false);
	txt_nomeFornecedor.setEnabled(true);
	cb_bairroFornecedor.setEnabled(true);
	txt_enderecoFornecedor.setEnabled(true);
	txt_numeroFornecedor.setEnabled(true);
	txt_cnpjFornecedor.setEnabled(true);
	txt_celular.setEnabled(true);
	txt_telefoneFornecedor.setEnabled(true);
	cb_bairroFornecedor.setEnabled(true);
	bt_cancelar.setEnabled(true);
	bt_pesquisar.setEnabled(false);
	txt_pesquisar.setEnabled(false);
    }//GEN-LAST:event_tbl_fornecedoresMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(FrmFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(FrmFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(FrmFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(FrmFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new FrmFornecedores().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bt_cancelar;
    public javax.swing.JButton bt_editar;
    public javax.swing.JButton bt_excluir;
    public javax.swing.JButton bt_novo;
    public javax.swing.JButton bt_pesquisar;
    public javax.swing.JButton bt_salvar;
    public javax.swing.JComboBox<String> cb_bairroFornecedor;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel10;
    public javax.swing.JPanel jPanel11;
    public javax.swing.JPanel jPanel12;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JPanel jPanel6;
    public javax.swing.JPanel jPanel7;
    public javax.swing.JPanel jPanel8;
    public javax.swing.JPanel jPanel9;
    public javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JLabel lbl_data;
    public javax.swing.JLabel lbl_horario;
    public javax.swing.JLabel lbl_idFornecedor;
    public javax.swing.JTable tbl_fornecedores;
    public javax.swing.JFormattedTextField txt_celular;
    public javax.swing.JTextField txt_cidade;
    public javax.swing.JFormattedTextField txt_cnpjFornecedor;
    public javax.swing.JTextField txt_enderecoFornecedor;
    public javax.swing.JTextField txt_estado;
    public javax.swing.JTextField txt_nomeFornecedor;
    public javax.swing.JTextField txt_numeroFornecedor;
    public javax.swing.JTextField txt_pesquisar;
    public javax.swing.JFormattedTextField txt_telefoneFornecedor;
    // End of variables declaration//GEN-END:variables
}
