/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ControleEstoque.visao;

import br.com.ControleEstoque.Utilitarios.AtualizadorHora;
import br.com.ControleEstoque.controle.ControleProdutos;
import br.com.ControleEstoque.dal.ConexaoBD;
import br.com.ControleEstoque.modelo.ModeloProdutos;
import br.com.ControleEstoque.modelo.ModeloTabela;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Cleiton
 */
public class FrmProdutos extends javax.swing.JFrame {
    ConexaoBD conex = new ConexaoBD();
    ModeloProdutos mod = new ModeloProdutos();
    ControleProdutos control = new ControleProdutos();
    /**
     * Creates new form FrmProdutos
     */
    public FrmProdutos() {
	initComponents();
	SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
	Date hoje = new Date();
	lbl_data.setText(df.format(hoje));
	AtualizadorHora.start(lbl_horario);
	preencherFornecedores();
	preencherTabela("select * from tbprodutos inner join tbfornecedores on id_fornecedorf = id_fornecedor order by nome_produto");
    }//FIM DA INICIALIZAÇÃO
    public void preencherFornecedores() {
	conex.Conexao();

	try {
	    conex.executaSql("select * from tbfornecedores order by nome_fornecedor");
	    conex.rs.first();
	    cb_fornecedor.removeAllItems();
	    do {
		cb_fornecedor.addItem(conex.rs.getString("nome_fornecedor"));
	    } while (conex.rs.next());
	} catch (SQLException ex) {
	    JOptionPane.showMessageDialog(null, "Erro ao preencher a cb_nomeFornecedor" + ex);
	}
	conex.desconecta();
    }// FIM DO METODO

    public void preencherTabela(String sql) {
	ArrayList dados = new ArrayList();
	String[] colunas = new String[]{"Id", "Produto","Código Barras", "Est.Atual", "Est.Minimo", "Est.Máximo", "Preço Compra", "Preço Venda","Localização"};
	conex.Conexao();
	conex.executaSql(sql);
	try {
	    conex.rs.first();
	    do {
		dados.add(new Object[]{conex.rs.getInt("id_produto"), conex.rs.getString("nome_produto"), conex.rs.getString("codigo_barras"), conex.rs.getString("quantidade_produto"), conex.rs.getString("estoqueMin_produto"), conex.rs.getString("estoqueMax_produto"), conex.rs.getFloat("precoCompra_produto"), conex.rs.getFloat("precoVenda_produto"),conex.rs.getString("local_produto")});
	    } while (conex.rs.next());

	} catch (Exception ex) {
	    JOptionPane.showMessageDialog(null, "Erro ao preencher ArrayList" + ex);
	}
	ModeloTabela modelo = new ModeloTabela(dados, colunas);
	tbl_produtos.setModel(modelo);
	tbl_produtos.getColumnModel().getColumn(0).setPreferredWidth(50);
	tbl_produtos.getColumnModel().getColumn(0).setResizable(false);
	tbl_produtos.getColumnModel().getColumn(1).setPreferredWidth(225);
	tbl_produtos.getColumnModel().getColumn(1).setResizable(false);
	tbl_produtos.getColumnModel().getColumn(2).setPreferredWidth(180);
	tbl_produtos.getColumnModel().getColumn(2).setResizable(false);
	tbl_produtos.getColumnModel().getColumn(3).setPreferredWidth(100);
	tbl_produtos.getColumnModel().getColumn(3).setResizable(false);
	tbl_produtos.getColumnModel().getColumn(4).setPreferredWidth(100);
	tbl_produtos.getColumnModel().getColumn(4).setResizable(false);
	tbl_produtos.getColumnModel().getColumn(5).setPreferredWidth(100);
	tbl_produtos.getColumnModel().getColumn(5).setResizable(false);
	tbl_produtos.getColumnModel().getColumn(6).setPreferredWidth(100);
	tbl_produtos.getColumnModel().getColumn(6).setResizable(false);
	tbl_produtos.getColumnModel().getColumn(7).setPreferredWidth(100);
	tbl_produtos.getColumnModel().getColumn(7).setResizable(false);
	tbl_produtos.getColumnModel().getColumn(8).setPreferredWidth(100);
	tbl_produtos.getColumnModel().getColumn(8).setResizable(false);
	tbl_produtos.getTableHeader().setReorderingAllowed(false);
	tbl_produtos.setAutoResizeMode(tbl_produtos.AUTO_RESIZE_OFF);
	tbl_produtos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
	conex.desconecta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_horario = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lbl_data = new javax.swing.JLabel();
        lbl_idProduto = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_codigoProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cb_fornecedor = new javax.swing.JComboBox<>();
        txt_pesquisar = new javax.swing.JTextField();
        bt_pesquisar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_descricaoProduto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_quantidadeProduto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_precoCompra = new javax.swing.JTextField();
        txt_precoVenda = new javax.swing.JTextField();
        txt_local = new javax.swing.JTextField();
        txt_estoqueMin = new javax.swing.JTextField();
        txt_estoqueMax = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        bt_novo = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        bt_salvar = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        bt_cancelar = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        bt_editar = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        bt_excluir = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbl_produtos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setPreferredSize(new java.awt.Dimension(1340, 110));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Formulário Cadastro de Produtos");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lbl_horario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_horario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_horario.setText("Data");
        lbl_horario.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_horario, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_horario, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lbl_data.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_data.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_data.setText("Data");
        lbl_data.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_data, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        lbl_idProduto.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_idProduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_idProduto.setText("01");
        lbl_idProduto.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Cod :");
        jLabel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_idProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                .addGap(207, 207, 207)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_idProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(19, 19, 19))))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Código de Barras :");
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txt_codigoProduto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_codigoProduto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_codigoProduto.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Fornecedor :");
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        cb_fornecedor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cb_fornecedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_fornecedor.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        cb_fornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cb_fornecedorMouseEntered(evt);
            }
        });

        txt_pesquisar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_pesquisar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_pesquisar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        bt_pesquisar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bt_pesquisar.setText("Pesquisar");
        bt_pesquisar.setToolTipText("Pesquise por um Cliente");
        bt_pesquisar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        bt_pesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pesquisarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Descrição do Produto :");
        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txt_descricaoProduto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_descricaoProduto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_descricaoProduto.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Quantidade :");
        jLabel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txt_quantidadeProduto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_quantidadeProduto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_quantidadeProduto.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Preço de Compra :");
        jLabel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Preço de Venda :");
        jLabel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Pesquise um Produto :");
        jLabel10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Localização :");
        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Estoque Minimo :");
        jLabel11.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Estoque Máximo :");
        jLabel12.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txt_precoCompra.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_precoCompra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_precoCompra.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txt_precoVenda.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_precoVenda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_precoVenda.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txt_local.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_local.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_local.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txt_estoqueMin.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_estoqueMin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_estoqueMin.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txt_estoqueMax.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_estoqueMax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_estoqueMax.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txt_quantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(345, 345, 345))
                    .addComponent(txt_descricaoProduto)
                    .addComponent(txt_codigoProduto)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_precoVenda)
                            .addComponent(txt_precoCompra)
                            .addComponent(cb_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(150, 150, 150)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_local)
                            .addComponent(txt_estoqueMin)
                            .addComponent(txt_estoqueMax)
                            .addComponent(txt_pesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                        .addContainerGap(227, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(bt_pesquisar)
                        .addGap(324, 324, 324))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_codigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txt_local, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_descricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txt_estoqueMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_quantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txt_estoqueMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cb_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_precoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_precoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txt_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(bt_pesquisar)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txt_codigoProduto, txt_descricaoProduto, txt_estoqueMax, txt_estoqueMin, txt_local, txt_pesquisar, txt_quantidadeProduto});

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        bt_novo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bt_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ControleEstoque/icones/add.png"))); // NOI18N
        bt_novo.setText("Novo");
        bt_novo.setToolTipText("Faça um novo Registro");
        bt_novo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        bt_novo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_novoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_novo, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_novo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        bt_salvar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bt_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ControleEstoque/icones/save-icon.png"))); // NOI18N
        bt_salvar.setText("Salvar");
        bt_salvar.setToolTipText("Salve um novo registro");
        bt_salvar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        bt_salvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_salvar.setEnabled(false);
        bt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_salvar, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_salvar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        bt_cancelar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bt_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ControleEstoque/icones/cancel-icon.png"))); // NOI18N
        bt_cancelar.setText("Cancelar");
        bt_cancelar.setToolTipText("Limpar os Campos");
        bt_cancelar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        bt_cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_cancelar.setEnabled(false);
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_cancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        bt_editar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bt_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ControleEstoque/icones/File-edit-icon.png"))); // NOI18N
        bt_editar.setText("Editar");
        bt_editar.setToolTipText("Atualizar um registro");
        bt_editar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        bt_editar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_editar.setEnabled(false);
        bt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_editar, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_editar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        bt_excluir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bt_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ControleEstoque/icones/delete.png"))); // NOI18N
        bt_excluir.setText("Excluir");
        bt_excluir.setToolTipText("Ecluir permanentemente um registro");
        bt_excluir.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        bt_excluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_excluir.setEnabled(false);
        bt_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_excluir, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_excluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Produtos  Cadastrados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        tbl_produtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_produtos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_produtosMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tbl_produtos);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 1058, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1330, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1366, 799));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cb_fornecedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_fornecedorMouseEntered

    }//GEN-LAST:event_cb_fornecedorMouseEntered

    private void bt_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pesquisarActionPerformed
  	String pesquisa = txt_pesquisar.getText();
	if (pesquisa.equals("")) {
	    JOptionPane.showMessageDialog(null, "Digite um Produto a ser pesquisado"); 
	} else {
	mod.setPesquisa(txt_pesquisar.getText());
	ModeloProdutos model = control.pesquisarProdutos(mod);
	lbl_idProduto.setText(String.valueOf(model.getId_produto()));
	txt_descricaoProduto.setText(model.getNome_produto());
	txt_codigoProduto.setText(model.getCodigo_barras());
	txt_quantidadeProduto.setText(Integer.toString(model.getQuantidade_produto()));
	txt_precoCompra.setText(Float.toString(model.getPrecoCompra_produto()));
	txt_precoVenda.setText(Float.toString(model.getPrecoVenda_produto()));
	txt_estoqueMin.setText(Integer.toString(model.getEstoqueMin_produto()));
	txt_estoqueMax.setText(Integer.toString(model.getEstoqueMax_produto()));
	txt_local.setText(model.getLocal_produto());
	cb_fornecedor.setSelectedItem(model.getNome_fornecedor());
	bt_editar.setEnabled(true);
	bt_excluir.setEnabled(true); 
      }
    }//GEN-LAST:event_bt_pesquisarActionPerformed

    private void bt_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_novoActionPerformed
        lbl_idProduto.setText("");
        txt_codigoProduto.setText("");
        txt_descricaoProduto.setText("");
        txt_quantidadeProduto.setText("");
        txt_estoqueMax.setText("");
        txt_precoCompra.setText("");
	txt_precoVenda.setText("");
        txt_local.setText("");
        txt_estoqueMin.setText("");
        txt_pesquisar.setText("");
        txt_pesquisar.setEnabled(false);
        txt_codigoProduto.setEnabled(true);
        txt_descricaoProduto.setEnabled(true);
        txt_quantidadeProduto.setEnabled(true);
        txt_estoqueMax.setEnabled(true);
        txt_precoCompra.setEnabled(true);
        txt_local.setEnabled(true);
        txt_estoqueMin.setEnabled(true);
        cb_fornecedor.setEnabled(true);
        bt_salvar.setEnabled(true);
        bt_cancelar.setEnabled(true);
        bt_editar.setEnabled(false);
        bt_excluir.setEnabled(false);
        bt_pesquisar.setEnabled(false);
    }//GEN-LAST:event_bt_novoActionPerformed

    private void bt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salvarActionPerformed
     if (txt_descricaoProduto.getText().isEmpty() || txt_quantidadeProduto.getText().isEmpty()) {
	    JOptionPane.showMessageDialog(null, "há campos a serem preenchidos");
	} else {
	    mod.setNome_produto(txt_descricaoProduto.getText());
	    mod.setQuantidade_produto(Integer.parseInt(txt_quantidadeProduto.getText()));
	    mod.setCodigo_barras(txt_codigoProduto.getText());
	    mod.setPrecoCompra_produto(Float.parseFloat(txt_precoCompra.getText().replace(",", ".")));
	    mod.setPrecoVenda_produto(Float.parseFloat(txt_precoVenda.getText().replace(",", ".")));
	    mod.setEstoqueMin_produto(Integer.parseInt(txt_estoqueMin.getText()));
	    mod.setEstoqueMax_produto(Integer.parseInt(txt_estoqueMax.getText()));
	    mod.setLocal_produto(txt_local.getText());
	    mod.setNome_fornecedor(cb_fornecedor.getSelectedItem().toString());
	    control.AdicionarProdutos(mod);
	    preencherTabela("select * from tbprodutos inner join tbfornecedores on id_fornecedorf = id_fornecedor order by nome_produto");
	}
	lbl_idProduto.setText("");
	txt_descricaoProduto.setText("");
	txt_quantidadeProduto.setText("");
	txt_codigoProduto.setText("");
	txt_precoCompra.setText("");
	txt_precoVenda.setText("");
	txt_estoqueMin.setText("");
	txt_estoqueMax.setText("");
	txt_local.setText("");
    }//GEN-LAST:event_bt_salvarActionPerformed

    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
        lbl_idProduto.setText("");
        txt_codigoProduto.setText("");
        txt_descricaoProduto.setText("");
        txt_quantidadeProduto.setText("");
        txt_estoqueMax.setText("");
        txt_precoCompra.setText("");
	txt_precoVenda.setText("");
        txt_local.setText("");
        txt_estoqueMin.setText("");
        txt_pesquisar.setText("");
        txt_pesquisar.setEnabled(true);
        txt_codigoProduto.setEnabled(false);
        txt_descricaoProduto.setEnabled(false);
        txt_quantidadeProduto.setEnabled(false);
        txt_estoqueMax.setEnabled(false);
        txt_precoCompra.setEnabled(false);
	txt_precoVenda.setEnabled(false);
        txt_local.setEnabled(false);
        txt_estoqueMin.setEnabled(false);
        cb_fornecedor.setEnabled(false);
        bt_salvar.setEnabled(false);
        bt_cancelar.setEnabled(true);
        bt_editar.setEnabled(false);
        bt_excluir.setEnabled(false);
        bt_pesquisar.setEnabled(true);
    }//GEN-LAST:event_bt_cancelarActionPerformed

    private void bt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editarActionPerformed
   	mod.setId_produto(Integer.parseInt(lbl_idProduto.getText()));
	mod.setNome_produto(txt_descricaoProduto.getText());
	mod.setCodigo_barras(txt_codigoProduto.getText());
	mod.setQuantidade_produto(Integer.parseInt(txt_quantidadeProduto.getText()));
	mod.setPrecoCompra_produto(Float.parseFloat(txt_precoCompra.getText().replace(",", ".")));
	mod.setPrecoVenda_produto(Float.parseFloat(txt_precoVenda.getText().replace(",", ".")));
	mod.setEstoqueMin_produto(Integer.parseInt(txt_estoqueMin.getText()));
	mod.setEstoqueMax_produto(Integer.parseInt(txt_estoqueMax.getText()));
	mod.setLocal_produto(txt_local.getText());
	mod.setNome_fornecedor(cb_fornecedor.getSelectedItem().toString());
	control.EditarProdutos(mod);	
	preencherTabela("select * from tbprodutos inner join tbfornecedores on id_fornecedorf = id_fornecedor order by nome_produto");
	lbl_idProduto.setText("");
	txt_descricaoProduto.setText("");
	txt_codigoProduto.setText("");
	txt_quantidadeProduto.setText("");
	txt_precoCompra.setText("");
	txt_precoVenda.setText("");
	txt_estoqueMin.setText("");
	txt_estoqueMax.setText("");
	txt_local.setText("");
	txt_pesquisar.setText("");
    }//GEN-LAST:event_bt_editarActionPerformed

    private void bt_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluirActionPerformed
     	mod.setId_produto(Integer.parseInt(lbl_idProduto.getText()));
	mod.setNome_produto(txt_descricaoProduto.getText());
	mod.setCodigo_barras(txt_codigoProduto.getText());
	mod.setQuantidade_produto(Integer.parseInt(txt_quantidadeProduto.getText()));
	mod.setPrecoCompra_produto(Float.parseFloat(txt_precoCompra.getText().replace(",", ".")));
	mod.setPrecoVenda_produto(Float.parseFloat(txt_precoVenda.getText().replace(",", ".")));
	mod.setEstoqueMin_produto(Integer.parseInt(txt_estoqueMin.getText()));
	mod.setEstoqueMax_produto(Integer.parseInt(txt_estoqueMax.getText()));
	mod.setLocal_produto(txt_local.getText());
	mod.setNome_fornecedor(cb_fornecedor.getSelectedItem().toString());
        control.ExcluirProdutos(mod);
        lbl_idProduto.setText("");
	txt_descricaoProduto.setText("");
	txt_codigoProduto.setText("");
	txt_quantidadeProduto.setText("");
	txt_precoCompra.setText("");
	txt_precoVenda.setText("");
	txt_estoqueMin.setText("");
	txt_estoqueMax.setText("");
	txt_local.setText("");
	txt_pesquisar.setText("");
        preencherTabela("select * from tbprodutos inner join tbfornecedores on id_fornecedorf = id_fornecedor order by nome_produto");
    }//GEN-LAST:event_bt_excluirActionPerformed

    private void tbl_produtosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_produtosMouseClicked
  String nome_produto = "" + tbl_produtos.getValueAt(tbl_produtos.getSelectedRow(), 1);
	conex.Conexao();
	conex.executaSql("select * from tbprodutos inner join tbfornecedores on id_fornecedorf = id_fornecedor  where nome_produto='" + nome_produto + "'");
	try {
	    conex.rs.first();
	    lbl_idProduto.setText(Integer.toString(conex.rs.getInt("id_produto")));
	    txt_descricaoProduto.setText(conex.rs.getString("nome_produto"));
	    txt_quantidadeProduto.setText(Integer.toString(conex.rs.getInt("quantidade_produto")));
	    txt_codigoProduto.setText(conex.rs.getString("codigo_barras"));
	    txt_precoCompra.setText(Float.toString(conex.rs.getFloat("precoCompra_produto")));
	    txt_precoVenda.setText(Float.toString(conex.rs.getFloat("precoVenda_produto")));
	    txt_estoqueMin.setText(Integer.toString(conex.rs.getInt("estoqueMin_produto")));
	    txt_estoqueMax.setText(Integer.toString(conex.rs.getInt("estoqueMax_produto")));
	    txt_local.setText(conex.rs.getString("local_produto"));
	    cb_fornecedor.setSelectedItem(conex.rs.getString("nome_fornecedor"));
	} catch (Exception ex) {
	    JOptionPane.showMessageDialog(null, "Erro ao setar campos " + ex);
	}
	conex.desconecta();
	txt_descricaoProduto.setEnabled(true);
	txt_quantidadeProduto.setEnabled(true);
	txt_codigoProduto.setEnabled(true);
	txt_precoCompra.setEnabled(true);
	txt_precoVenda.setEnabled(true);
	txt_estoqueMin.setEnabled(true);
	txt_estoqueMax.setEnabled(true);
	txt_local.setEnabled(true);
	cb_fornecedor.setEnabled(true);
	bt_pesquisar.setEnabled(false);
	txt_pesquisar.setEnabled(false);

	bt_editar.setEnabled(true);
	bt_excluir.setEnabled(true);
	bt_cancelar.setEnabled(true);
	bt_salvar.setEnabled(false);
    }//GEN-LAST:event_tbl_produtosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(FrmProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(FrmProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(FrmProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(FrmProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new FrmProdutos().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bt_cancelar;
    public javax.swing.JButton bt_editar;
    public javax.swing.JButton bt_excluir;
    public javax.swing.JButton bt_novo;
    public javax.swing.JButton bt_pesquisar;
    public javax.swing.JButton bt_salvar;
    public javax.swing.JComboBox<String> cb_fornecedor;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel10;
    public javax.swing.JPanel jPanel11;
    public javax.swing.JPanel jPanel12;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JPanel jPanel6;
    public javax.swing.JPanel jPanel7;
    public javax.swing.JPanel jPanel8;
    public javax.swing.JPanel jPanel9;
    public javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JLabel lbl_data;
    public javax.swing.JLabel lbl_horario;
    public javax.swing.JLabel lbl_idProduto;
    public javax.swing.JTable tbl_produtos;
    public javax.swing.JTextField txt_codigoProduto;
    public javax.swing.JTextField txt_descricaoProduto;
    public javax.swing.JTextField txt_estoqueMax;
    public javax.swing.JTextField txt_estoqueMin;
    public javax.swing.JTextField txt_local;
    public javax.swing.JTextField txt_pesquisar;
    public javax.swing.JTextField txt_precoCompra;
    public javax.swing.JTextField txt_precoVenda;
    public javax.swing.JTextField txt_quantidadeProduto;
    // End of variables declaration//GEN-END:variables
}
