/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ControleEstoque.visao;

/**
 *
 * @author Cleiton
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menCadastros = new javax.swing.JMenu();
        menBairros = new javax.swing.JMenuItem();
        menCadCidades = new javax.swing.JMenuItem();
        menCadEstados = new javax.swing.JMenuItem();
        menCadClientes = new javax.swing.JMenuItem();
        menCadUsuarios = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1272, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 588, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        menCadastros.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        menCadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/AutoEletrica/icones/cad.png"))); // NOI18N
        menCadastros.setText("Cadastros");
        menCadastros.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        menCadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadastrosActionPerformed(evt);
            }
        });

        menBairros.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        menBairros.setText("Cadastro de Bairros");
        menBairros.setToolTipText("");
        menBairros.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        menBairros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menBairrosActionPerformed(evt);
            }
        });
        menCadastros.add(menBairros);

        menCadCidades.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        menCadCidades.setText("Cadastro de Cidades");
        menCadCidades.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        menCadCidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadCidadesActionPerformed(evt);
            }
        });
        menCadastros.add(menCadCidades);

        menCadEstados.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        menCadEstados.setText("Cadastro de Estados");
        menCadEstados.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        menCadEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadEstadosActionPerformed(evt);
            }
        });
        menCadastros.add(menCadEstados);

        menCadClientes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        menCadClientes.setText("Cadastro de Clientes ");
        menCadClientes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        menCadClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadClientesActionPerformed(evt);
            }
        });
        menCadastros.add(menCadClientes);

        menCadUsuarios.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        menCadUsuarios.setText("Cadastro de Usuarios");
        menCadUsuarios.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        menCadUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadUsuariosActionPerformed(evt);
            }
        });
        menCadastros.add(menCadUsuarios);

        jMenuBar1.add(menCadastros);

        jMenu2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/AutoEletrica/icones/money.png"))); // NOI18N
        jMenu2.setText("Compras");
        jMenu2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenuItem1.setText("Cadastro de Produtos");
        jMenuItem1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jMenu2.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenuItem2.setText("Cadastro de Fornecedores");
        jMenuItem2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        setSize(new java.awt.Dimension(1316, 799));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menBairrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menBairrosActionPerformed
        FrmBairros bairros = new FrmBairros();
	bairros.setVisible(true);
    }//GEN-LAST:event_menBairrosActionPerformed

    private void menCadEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadEstadosActionPerformed
        FrmEstados estados = new FrmEstados();
	estados.setVisible(true);
    }//GEN-LAST:event_menCadEstadosActionPerformed

    private void menCadCidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadCidadesActionPerformed
        FrmCidades cidades = new  FrmCidades();
	cidades.setVisible(true);
    }//GEN-LAST:event_menCadCidadesActionPerformed

    private void menCadClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadClientesActionPerformed
        FrmClientes clientes = new FrmClientes();
	clientes.setVisible(true);
    }//GEN-LAST:event_menCadClientesActionPerformed

    private void menCadUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadUsuariosActionPerformed
        FrmUsuarios usuarios = new FrmUsuarios();
	usuarios.setVisible(true);
    }//GEN-LAST:event_menCadUsuariosActionPerformed

    private void menCadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadastrosActionPerformed
        FrmClientes clientes = new FrmClientes();
	clientes.setVisible(true);
    }//GEN-LAST:event_menCadastrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new TelaPrincipal().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu jMenu2;
    public javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuItem1;
    public javax.swing.JMenuItem jMenuItem2;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JMenuItem menBairros;
    public javax.swing.JMenuItem menCadCidades;
    public javax.swing.JMenuItem menCadClientes;
    public javax.swing.JMenuItem menCadEstados;
    public javax.swing.JMenuItem menCadUsuarios;
    public javax.swing.JMenu menCadastros;
    // End of variables declaration//GEN-END:variables
}
